webpackJsonp([0],[,,,,,,,,,,,,function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,r){var o=i(r,2),a=o[0],l=o[1];a&&a.renderOnly||l.load(a?a.user:null).then(function(e){t.addClass("c"+e.length)})}var t={require:["^?editableSite","brndmBlogSection"],link:e,restrict:"A",controller:a.default,controllerAs:"blog",bindToController:!0,templateUrl:function(e,t){return"themes/directives/blog-section/blog-section"+(t.slider?"-slider":"")+".html"}};
return t};
var o=n(34),a=r(o)},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,i){var o=r(i,2),a=o[0],l=o[1];a&&a.renderOnly||(l.element=t)}var t={require:["^?editableSite","brndmBsCollapseScrollAnchor"],link:e,controller:function e(){n(this,e)}};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=["$document","$timeout",function(e,t){"ngInject";function r(r,i,o,a){function l(){var n=d.$activeIndexes(),r=void 0;r=n>-1&&n<d.$targets.length?i:f.element;var o=void 0;if(s){var a=e.find(".theme .container.sections");
o=a.length?a:e.find(".theme .site-content")}else o=e;r&&t(function(){return o.duScrollToElementAnimated(r,null,700)})}var u=n(a,4),s=u[0],c=u[1],d=u[2],f=u[3];c&&c.renderOnly||(d.$viewChangeListeners.push(l),l())}var i={require:["^?editorFrame","^?editableSite","^bsCollapse","^brndmBsCollapseScrollAnchor"],link:r};
return i}]},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,2),a=o[0],l=o[1];a&&a.renderOnly||t.on("click",function(){e.$apply(function(){return l.$setActive(-1)})})}var t={require:["^?editableSite","^bsCollapse"],link:e};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=["$http",function(e){"ngInject";var t=this;this.senderName="",this.senderEmail="",this.message="",this.submit=function(){t.success=!1,t.error=!1,t.isSending=!0;var n="https://"+Brndm.apiEndpoint+"/v1/message/new/"+Brndm.profile.id;e.post(n,{from:t.senderEmail,name:t.senderName,message:t.message}).then(function(){t.success=!0,t.senderName="",t.senderEmail="",t.message=""}).catch(function(){t.error=!0}).finally(function(){t.isSending=!1})}}]},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,3),a=o[0],l=o[1],u=o[2];l||a&&a.renderOnly||t.on("submit",function(e){e.preventDefault(),u.submit()})}var t={require:["^?editableSite","^?editorFrame","brndmContactForm"],link:e,controller:"BrndmContactFormController",controllerAs:"brndmContactForm",bindToController:!0};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||l||t.on("click",function(){u.gotoSection(r.brndmMenuItem)})}var t={require:["^?editableSite","^?editor","^brndmNavigation"],link:e};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,2),a=o[0],l=o[1];l||a&&a.renderOnly||t.on("click",function(){Brndm.embedded?Brndm.embedded.messageUser():window.location="https://"+Brndm.webEndpoint+"/messages/"+Brndm.profile.slug})}var t={require:["^?editableSite","^?editor"],link:e};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,3),a=o[0],l=o[1],u=o[2],s=t.siblings("nav");
a&&a.renderOnly||l||(t.on("click",function(){t.toggleClass("close")}),s.on("click",function(){t.removeClass("close"),e.$apply(function(){return u.$setActive(-1)})}))}var t={require:["^?editableSite","^?editor","^bsCollapse"],link:e};
return t}},function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,r){var o=i(r,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||(u.link(t,l),l.registerTargetGroup(u),e.$on("$destroy",function(){return l.unregisterTargetGroup(u)}))}var t={scope:!0,require:["^?editableSite","^brndmModal","brndmModalTargetGroup"],link:e,controller:a.default,controllerAs:"brndmModalTargetGroup"};
return t};
var o=n(35),a=r(o)},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,i){var o=r(i,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||(u.element=t,l.registerTarget(u),e.$on("$destroy",function(){return l.unregisterTarget(u)}))}var t={scope:!0,require:["^?editableSite","^brndmModalTargetGroup","brndmModalTarget"],link:e,controller:function e(){n(this,e)},controllerAs:"brndmModalTarget"};
return t}},function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,r){var o=i(r,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||u.link(t,l)}var t={scope:!0,require:["^?editableSite","^brndmModal","brndmModalToggleGroup"],link:e,controller:a.default};
return t};
var o=n(36),a=r(o)},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,i){var o=r(i,2),a=o[0],l=o[1];a&&a.renderOnly||t.on("click",function(){e.$apply(function(){return l.setActive(t)})})}var t={require:["^?editableSite","^brndmModalToggleGroup"],link:e,controller:function e(){n(this,e)}};
return t}},function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,r){var o=i(r,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||u.link(t,l)}var t={controller:a.default,controllerAs:"brndmModal",require:["^?editableSite","^?editorFrame","brndmModal"],link:e};
return t};
var o=n(37),a=r(o)},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=function(){function e(t,r){"ngInject";n(this,e),this.$document=t,this.$element=r}return e.$inject=["$document","$element"],r(e,[{key:"link",value:function(e){this.editorFrame=e}},{key:"gotoSection",value:function(e){var t=void 0;t=_.isObject(e)?e.id:e;var n=this.$element.find("#"+t),r=void 0;this.editorFrame?(r=this.$element.find(".container.sections"),r.length||(r=this.$element.find(".site-content"))):r=this.$document,r.duScrollToElementAnimated(n)}}]),e}();
t.default=i},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,3),a=o[0],l=o[1],u=o[2];a&&a.renderOnly||(u.link(l),e.$on("goto-section",function(e,t){u.gotoSection(t)}))}var t={require:["^?editableSite","^?editorFrame","^brndmNavigation"],link:e,controller:"BrndmNavigationController",controllerAs:"brndmNavigation"};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=["$animate",function(e){"ngInject";function t(t,r,i,o){function a(){var t=void 0;t=s.hasPrev||s.hasNext?"removeClass":"addClass",e[t](r,"ng-hide")}var l=n(o,2),u=l[0],s=l[1];u&&u.renderOnly||(s.viewChangeListeners.push(a),a())}var r={require:["^?editableSite","^slider"],link:t};
return r}]},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){var o=n(i,2),a=o[0],l=o[1];a&&a.renderOnly||(e.$on("$destroy",function(){l.unregisterItem(t)}),l.registerItem(t))}var t={require:["^?editableSite","^slider"],link:e};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){function o(){u.hasNext?t.removeAttr("disabled"):t.attr("disabled","disabled")}var a=n(i,2),l=a[0],u=a[1];l&&l.renderOnly||(t.on("click",function(){e.$apply(function(){return u.next()})}),u.viewChangeListeners.push(o),o())}var t={require:["^?editableSite","^slider"],link:e};
return t}},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0});
var n=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,r,i){function o(){u.hasPrev?t.removeAttr("disabled"):t.attr("disabled","disabled")}var a=n(i,2),l=a[0],u=a[1];l&&l.renderOnly||(t.on("click",function(){e.$apply(function(){return u.prev()})}),u.viewChangeListeners.push(o),o())}var t={require:["^?editableSite","^slider"],link:e};
return t}},function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=function(){function e(e,t){var n=[],r=!0,i=!1,o=void 0;try{for(var a,l=e[Symbol.iterator]();
!(r=(a=l.next()).done)&&(n.push(a.value),!t||n.length!==t);
r=!0);
}catch(e){i=!0,o=e}finally{try{!r&&l.return&&l.return()}finally{if(i)throw o}}return n}return function(t,n){if(Array.isArray(t))return t;if(Symbol.iterator in Object(t))return e(t,n);
throw new TypeError("Invalid attempt to destructure non-iterable instance")}}();
t.default=function(){"ngInject";function e(e,t,n,r){function o(){u.refresh()}var a=i(r,2),l=a[0],u=a[1];l&&l.renderOnly||(e.$on("$destroy",function(){removeResizeListener(t[0],o)}),addResizeListener(t[0],o))}var t={scope:!0,require:["^?editableSite","^slider"],link:e,controller:a.default,controllerAs:"slider"};
return t};
var o=n(38),a=r(o)},function(e,t){"use strict";function n(e){"ngInject";angular.extend(e.defaults,{startCollapsed:!0})}n.$inject=["$collapseProvider"],Object.defineProperty(t,"__esModule",{value:!0}),t.default=n},function(e,t){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=["$window","publicBlogService",function(e,t){"ngInject";var n=this,r=void 0;e.Brndm&&(r=e.Brndm.profile),this.load=function(e){return t.getAll(e||r).then(function(e){return n.posts=e.items.slice(0,3),n.posts})}}]},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=function(){function e(){"ngInject";n(this,e),this.targets=[]}return r(e,[{key:"link",value:function(e,t){this.element=e,this.modal=t}},{key:"registerTarget",value:function(e){this.targets.push(e)}},{key:"unregisterTarget",value:function(e){_.pull(this.targets,e)}},{key:"setActive",value:function(e){this.activeTarget=e}},{key:"_getSiblingTarget",value:function(e){var t=this.element.find("[brndm-modal-target]"),n=t.index(this.activeTarget.element),r=t[n+e];return r?_.find(this.targets,{element:angular.element(r)}):null}},{key:"getNext",value:function(){return this.activeTarget?this._getSiblingTarget(1):null}},{key:"getPrev",value:function(){return this.activeTarget?this._getSiblingTarget(-1):null}}]),e}();
t.default=i},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=function(){function e(){"ngInject";n(this,e)}return r(e,[{key:"link",value:function(e,t){this.element=e,this.modal=t}},{key:"setActive",value:function(e){var t=this.element.find("[brndm-modal-toggle]").index(e);
this.modal.setActiveByToggle(t,this.element)}}]),e}();
t.default=i},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i=function(){function e(t){"ngInject";n(this,e),this.activeItem=null,this.$scope=t,this.targetGroups=[],this.viewChangeListeners=[],this.$body=angular.element("body")}return e.$inject=["$scope"],r(e,[{key:"link",value:function(e,t){this.element=e,this.editorFrame=t}},{key:"registerTargetGroup",value:function(e){this.targetGroups.push(e)}},{key:"unregisterTargetGroup",value:function(e){_.pull(this.targetGroups,e)}},{key:"setActiveByToggle",value:function(e,t){var n=this.element.find("[brndm-modal-toggle-group]").index(t),r=angular.element(this.element.find("[brndm-modal-target-group]")[n]),i=_.find(this.targetGroups,{element:r}),o=angular.element(r.find("[brndm-modal-target]")[e]),a=_.find(i.targets,{element:o});
this.setActive(a,i)}},{key:"setActive",value:function(e,t){this.activeTargetGroup=t,this.activeTarget=e,this.activeTargetGroup.setActive(this.activeTarget),this.editorFrame||this.$body.addClass("modal-opened"),this.$scope.$emit("theme:modal-opened"),_.each(this.viewChangeListeners,function(e){return e()})}},{key:"reset",value:function(){this.activeTarget=null,this.activeTargetGroup=null,this.editorFrame||this.$body.removeClass("modal-opened"),_.each(this.viewChangeListeners,function(e){return e()})}}]),e}();
t.default=i},function(e,t){"use strict";function n(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")}Object.defineProperty(t,"__esModule",{value:!0});
var r=function(){function e(e,t){for(var n=0;n<t.length;n++){var r=t[n];r.enumerable=r.enumerable||!1,r.configurable=!0,"value"in r&&(r.writable=!0),Object.defineProperty(e,r.key,r)}}return function(t,n,r){return n&&e(t.prototype,n),r&&e(t,r),t}}(),i={},o=function(){function e(t,r,o){"ngInject";var a=this;n(this,e),this.$scope=r,this.options=_.clone(i),_.each(["minItemWidth","maxItems"],function(e){_.isUndefined(o[e])||("minItemWidth"===e||"maxItems"===e?a.options[e]=parseInt(o[e],10):a.options[e]=o[e])}),this.items=[],this.viewChangeListeners=[],this.sliderContent=t.find("slider-content")}return e.$inject=["$element","$scope","$attrs"],r(e,[{key:"registerItem",value:function(e){this.items.push(e),this.refresh()}},{key:"unregisterItem",value:function(e){_.pull(this.items,e),this.refresh()}},{key:"setPosition",value:function(e){this.position=e,this.sliderContent.scrollLeft(e)}},{key:"setPositionAnimated",value:function(e){this.position=e,this.sliderContent.duScrollLeftAnimated(e),this.updatePosition()}},{key:"prev",value:function(){this.setPositionAnimated(this.position-this.itemWidth)}},{key:"next",value:function(){this.setPositionAnimated(this.position+this.itemWidth)}},{key:"reveal",value:function(e){e=Math.min(this.items.length+1-this.options.maxItems,e);
var t=e*this.itemWidth;this.setPositionAnimated(t)}},{key:"refresh",value:function(){var e=this,t=this.viewportWidth=this.sliderContent.width(),n=void 0,r=Math.min(this.items.length,this.options.maxItems);
do n=t/r,--r;while(n<this.options.minItemWidth&&r>0);
var i=this.itemWidth/n;this.setPosition(this.position/i),this.itemWidth=n,this.contentWidth=this.items.length*this.itemWidth,_.each(this.items,function(t){t.css("width",e.itemWidth)}),this.updatePosition()}},{key:"updatePosition",value:function(){this.contentWidth<=this.viewportWidth&&0!==this.position&&this.setPosition(0),this.hasPrev=this.position>0,this.hasNext=this.viewportWidth<Math.floor(this.contentWidth-this.position),_.each(this.viewChangeListeners,function(e){return e()})}},{key:"getSlideItems",value:function(e,t,n){var r=t-e;return new Array(Math.min(r,n))}}]),e}();
t.default=o},,,,,,,,function(e,t,n){"use strict";function r(e){return e&&e.__esModule?e:{default:e}}Object.defineProperty(t,"__esModule",{value:!0});
var i=n(3),o=r(i),a=n(2),l=r(a),u=n(18),s=r(u),c=n(20),d=r(c),f=n(19),v=r(f),h=n(17),m=r(h),y=n(16),p=r(y),b=n(32),g=r(b),w=n(29),S=r(w),_=n(31),j=r(_),k=n(30),O=r(k),A=n(28),I=r(A),T=n(14),$=r(T),M=n(13),x=r(M),C=n(15),P=r(C),E=n(25),B=r(E),q=n(24),G=r(q),W=n(23),N=r(W),F=n(22),L=r(F),z=n(21),R=r(z),U=n(27),D=r(U),J=n(26),H=r(J),K=n(12),Q=r(K),V=n(33),X=r(V),Y=n(9),Z=r(Y),ee=n(8),te=r(ee),ne=n(10),re=r(ne),ie=n(11),oe=r(ie),ae=n(6),le=r(ae),ue=n(4),se=r(ue),ce=n(5),de=r(ce),fe=n(1),ve=r(fe),he=n(7),me=r(he),ye="brndm-themes";angular.module(ye,["ngAnimate","ngTouch","ngSanitize","mgcrea.ngStrap.collapse","duScroll"]).factory("Insight",le.default).factory("Contact",se.default).factory("UserContact",de.default).factory("resizedImage",me.default).constant("hostname",ve.default).config(X.default).directive("resizeIframe",o.default).directive("brndmMenuItem",s.default).directive("brndmMobileMenu",d.default).directive("brndmMessageMeBtn",v.default).directive("brndmContactForm",m.default).controller("BrndmContactFormController",p.default).directive("brndmBsCollapseScroll",$.default).directive("brndmBsCollapseScrollAnchor",x.default).directive("brndmBsCollapseToggleCurrent",P.default).directive("brndmModal",B.default).directive("brndmModalToggle",G.default).directive("brndmModalToggleGroup",N.default).directive("brndmModalTarget",L.default).directive("brndmModalTargetGroup",R.default).directive("brndmNavigation",D.default).controller("BrndmNavigationController",H.default).directive("brndmBlogSection",Q.default).directive("slider",g.default).directive("sliderItem",S.default).directive("sliderPrev",j.default).directive("sliderNext",O.default).directive("sliderButtons",I.default).directive("backgroundSrc",l.default).service("ApiService",Z.default).service("analyticsService",te.default).service("publicBlogService",re.default).service("publicProfileService",oe.default),t.default=ye}],[46]),angular.module("brndm-themes").run(["$templateCache",function(e){e.put("themes/directives/blog-section/blog-section-slider.html",'<slider ng-class="[\'slider list content\', {\'multiple-listings\': blog.posts.length > 1}]" data-max-items="1"><slider-content><slider-content-wrapper><slider-item ng-repeat="post in blog.posts | limitTo: 3" ng-if="$index % 2 === 0"><div class="listing-wrapper clearfix" section="section" ng-model="blog.posts[$parent.$index + $index]" ng-repeat="indexOffset in slider.getSlideItems($parent.$index, blog.posts.length, 2) track by $index"><div class="listing clearfix"><h3>{{ blog.posts[$parent.$index + $index].title }}</h3><div class="image" ng-if="blog.posts[$parent.$index + $index].previewImage" background-src="{{ blog.posts[$parent.$index + $index].previewImage }}"></div><div class="text"><p>{{ blog.posts[$parent.$index + $index].previewText }}...&nbsp; <a class="read-more" ng-href="{{ blog.posts[$parent.$index + $index].url }}">Read more</a></p></div></div></div></slider-item></slider-content-wrapper></slider-content><div slider-buttons=""><button slider-prev="" class="slick-prev">Previous</button> <button slider-next="" class="slick-next">Next</button></div></slider>'),e.put("themes/directives/blog-section/blog-section.html",'<div class="item" ng-repeat="item in blog.posts | limitTo: 4"><h3><a ng-href="{{ item.url }}">{{ ::item.title }}</a></h3><div class="image" ng-if="item.previewImage" background-src="{{ item.previewImage }}"></div><p class="item-text">{{ ::item.previewText }}...&nbsp; <a ng-href="{{ item.url }}" class="read-more">Read more</a></p><div class="clearfix"></div><small class="item-date">{{+item.published | date:"MMM d, yyyy"}}</small></div><a class="btn btn-success" ui-sref="ideas" ng-if="!editableSite.renderOnly && blog.posts && blog.posts.length === 0">Publish your first blog post to show here</a>')}]);
